//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BATCapstoneSP2017.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public Nullable<int> MenuItemID { get; set; }
        public string URLName { get; set; }
        public byte[] Image1 { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
    }
}
